Added basic client with homepage
monkey-corp/MonkeyCorp.fr pull request #39
Opened 2024-10-07 05:36 UTC by ianb1204

Ticket #23  -  Client side

2024-10-07 10:07 UTC, JMazat requested changes
Il faut ajouter dans le .gitignore de quoi gérer les Zone.Identifier pour ceux qui sont sur WSL

Si c'est pas normal que le "Soon" revienne à la ligne alors il faudrait corriger le style (tester les résolutions ?) 

Testé en 1080p sur chrome

2024-10-08 17:27 UTC, LeVraiPicou commented on packages/site/src/components/DotLoader.scss
> +        width: 160px;
170

2024-10-08 17:27 UTC, LeVraiPicou commented on packages/site/src/components/DotLoader.scss
> +    width: 200px;
210

2024-10-08 17:48 UTC, LeVraiPicou commented
> Il faut ajouter dans le .gitignore de quoi gérer les Zone.Identifier pour ceux qui sont sur WSL
> 
> Si c'est pas normal que le "Soon" revienne à la ligne alors il faudrait corriger le style (tester les résolutions ?)
> 
> Testé en 1080p sur chrome

c'est clairement au dev de pas push de la d en vrai

2024-10-08 17:55 UTC, closed without merging